AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  KeyPair:
    Description: Select your key-pair  
    Type: AWS::EC2::KeyPair::KeyName
  
Resources:
  CFNInstanceConvertRoman:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: !Ref KeyPair 
      SecurityGroups:
        - !Ref CFNConvertRomanSecGroup
      Tags:
        - Key: Name 
          Value: !Sub Web Server of ${AWS::StackName} Stack
      UserData: !Base64 |
        #!/bin/bash
        yum update -y 
        pip3 install flask 
        yum install git -y 
        cd /home/ec2-user
        git clone https://github.com/8mehmet11/CloudFormationTemplate.git 
        cd 
        cd /home/ec2-user/CloudFormationTemplate/Project-001-Roman-Numerals-Converter/ 
        python3 app.py 
 

  CFNConvertRomanSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP for CFN Instance  # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
    
  
Outputs:
  WebSiteURL:
    Description: Roman Numerals Converter Application URL
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt CFNInstanceConvertRoman.PublicDnsName
